stages:
  - triggers

# Create a trigger for running the frontend workflow
trigger_frontend_workflow:
  stage: triggers
  # When the trigger fires it will run the frontend workflow
  trigger:
    include: product/.gitlab/workflows/frontend.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - product/frontend/**
    - when: manual

# Create a trigger for running the backend workflow
trigger_backend_workflow:
  stage: triggers
  trigger:
    include: product/.gitlab/workflows/backend.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - product/backend/application/**
    - when: manual