stages:
  - triggers

# Create a trigger for running the frontend workflow
trigger_frontend_workflow:
  stage: triggers
  # When the trigger fires it will run the frontend workflow
  trigger:
    include: product/.gitlab/workflows/frontend.yml
  rules:
    - changes:
        - product/frontend/**

# Create a trigger for running the backend workflow
trigger_backend_workflow:
  stage: triggers
  trigger:
    include: product/.gitlab/workflows/backend.yml
  rules:
    - changes:
        - product/backend/application/**
