stages:
  - triggers

# Create a trigger for running the frontend workflow
trigger_frontend_workflow:
  stage: triggers
  trigger:
    include: product/.gitlab/workflows/frontend.yml

# Create a trigger for running the backend workflow
trigger_backend_workflow:
  stage: triggers
  trigger:
    include: product/.gitlab/workflows/backend.yml
