
stages:
  - triggers

# Create a trigger for running the frontend workflow
trigger_frontend_workflow:
  stage: triggers
  # When the trigger fires it will run the frontend workflow
  trigger:
    include: ./product/.gitlab-ci/workflows/frontend.yml
  # The frontend workflow will only run when changes are made to the frontend directory
  rules:
    - when: 
        manual
    - changes:
        - ./product/frontend/*

# Create a trigger for running the frontend workflow
trigger_backend_workflow:
  stage: triggers
  # When the trigger fires it will run the frontend workflow
  trigger:
    include: ./product/.gitlab-ci/workflows/backend.yml
  # The frontend workflow will only run when changes are made to the backend directory
  rules:
    - when: 
        manual
    - changes:
        - ./product/backend/application/*