stages:
  - triggers

# Create a trigger for running the frontend workflow
trigger_frontend_workflow:
  stage: triggers
  trigger:
    include: product/CICD/gitlab/frontend.yml

# Create a trigger for running the backend workflow
trigger_backend_workflow:
  stage: triggers
  trigger:
    include: product/CICD/gitlab/backend.yml

# This will be included after issues with the runners are resolved

# Run Terraform workflow if there are changes in the terraform directory
# trigger_terraform_workflow:
#   stage: triggers
#   rules:
#     - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "terraform-updates"'
#       changes:
#         - product/infrastructure/*
#       when: on_success
#     - when: manual
#   trigger:
#     include: product/.gitlab/workflows/terraform.yml