spring:
  application:
    name: backend
  profiles:
    active: test
    # This sets the active profile to test
  graphql:
    graphiql:
      enabled: true
      # This enables the graphiql interface
  datasource:
    url: jdbc:h2:mem:test
    username: user
    password: password
    # This should be the database url, username and password it is
    # currently set to work with a in memory h2 database for testing
# Actuator config
management:
  endpoints:
    web:
      base-path: "/details"
      # This should be the base path for the actuator endpoints
    jmx:
      exposure:
        include: "health"
        # This should be the actuator endpoints that you want to expose

api:
  key: "test"
  # This is to test the api key authentication