spring:
  application:
    name: backend
  profiles:
    active: test
    # This sets the active profile to test
  graphql:
    graphiql:
      enabled: true
      # This enables the graphiql interface
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          # This should be the cognito uri that is https://cognito-idp.<aws-region>.amazonaws.com/<cognito-pool-id>
  datasource:
    url: jdbc:h2:mem:test
    username: user
    password: password
    # This should be the database url, username and password it is
    # currently set to work with a in memory h2 database for testing
redis:
  host: 0.0.0.0
  port: 6379
# Actuator config
management:
  endpoints:
    web:
      base-path: "/details"
      # This should be the base path for the actuator endpoints
    jmx:
      exposure:
        include: "health"
        # This should be the actuator endpoints that you want to expose

jira:
  accessToken:
  email:
  url:
  projectKey:
# This should be the jira information for reporting bugs

api:
  key: "test"
  # This is to test the api key authentication

  server:
    max-http-request-header-size: 20000
  # This allows larger headers to be sent