services:
  final-project-dynamodb:
    container_name: final-project-dynamodb
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  final-project-backend:
    build:
      context: ./application/backendService/
      dockerfile: Dockerfile
      args:
        - TEST_COGNITO_JWT_URL=${TEST_COGNITO_JWT_URL}
    container_name: final-project-backend
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080/details/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - SPRING_ACTIVE_PROFILE=${SPRING_ACTIVE_PROFILE}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - COGNITO_JWT_URL=${COGNITO_JWT_URL}
      - API_KEY=${API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - IS_CHAT_ENABLED=${IS_CHAT_ENABLED}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - OPEN_API_PROJECT_ID=${OPEN_API_PROJECT_ID}
      - OPEN_API_ORGANIZATION_ID=${OPEN_API_ORGANIZATION_ID}
      - JIRA_ACCESS_TOKEN=${JIRA_ACCESS_TOKEN}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_URL=${JIRA_URL}
      - JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

  postgres:
    container_name: final-project-database
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase
    container_name: final-project-liquibase
    command: --url=${DATABASE_URL} --username=${POSTGRES_USER} --password=${POSTGRES_PASSWORD} --changelog-file=/changelogs/changelog-master.xml update
    volumes:
      - ./src:/liquibase/src
      - ./changelogs:/liquibase/changelogs
    depends_on:
      - "postgres"

  redis:
    container_name: final-project-redis
    image: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: final-project-zookeeper-local
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: final-project-kafka-local
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: final-project-zookeeper-local:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
