
image: maven:3.9.9-amazoncorretto-21-alpine

stages:
  - lint

before_script:
  - cd ./product/backend/

lint_backend:
  stage: lint
  script:
    - echo "Copying the test-application.yml into a application.yml file..."
    - cp ./application/backendService/src/main/resources/test-application.example.yml ./application/backendService/src/main/resources/application.yml
    - echo "Running backend linting..."
    - cd ./application/
    - mvn clean install
    - mvn checkstyle:check

