image: node:23-alpine

default:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - cd ./product/frontend/
    - echo "Installing dependencies..."
    - npm ci --cache .npm --prefer-offline

stages:
  - lint

lint_frontend:
  stage: lint
  script:
    - echo "Running frontend linting..."
    - npm run lint

knip_frontend:
  stage: lint
  script:
    - echo "Running frontend knip..."
    - npm run knip