services:
  final-project-frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    container_name: final-project-frontend-local
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://localhost:3000/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  final-project-backend:
    build:
      context: ../backend/application/
      dockerfile: Dockerfile
    container_name: final-project-backend-local
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080/details/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  postgres:
    container_name: final-project-database-local
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase
    container_name: final-project-liquibase-local
    command: --url=jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB} --username=${POSTGRES_USER} --password=${POSTGRES_PASSWORD} --changelog-file=/changelogs/changelog-master.xml update
    volumes:
      - ../backend/database/src:/liquibase/src
      - ../backend/database/changelogs:/liquibase/changelogs
    depends_on:
      - "postgres"