services:
  final-project-frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    container_name: final-project-frontend
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://localhost:3000/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  final-project-backend:
    build:
      context: ../backend/application/
      dockerfile: Dockerfile
    container_name: final-project-backend
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080/details/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s