services:
  final-project-apollo-gateway:
    build:
      context: ../backend/apolloGateway/
      dockerfile: Dockerfile
    container_name: final-project-apollo-gateway-local
    ports:
      - 4000:4000
    environment:
      API_KEY: ${API_KEY}
      ORIGIN_URL: http://final-project-frontend:3000
      BACKEND_SUBGRAPH_URL: http://final-project-backend:8080/graphql

  localstack:
    container_name: final-project-localstack
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"

  final-project-backend:
    build:
      context: ../backend/application/backendService/
      dockerfile: Dockerfile
      args:
        - TEST_COGNITO_JWT_URL=${TEST_COGNITO_JWT_URL}
    container_name: final-project-backend-local
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080/details/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - SPRING_ACTIVE_PROFILE=${SPRING_ACTIVE_PROFILE}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - COGNITO_JWT_URL=${COGNITO_JWT_URL}
      - API_KEY=${API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - IS_CHAT_ENABLED=${IS_CHAT_ENABLED}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - OPEN_API_PROJECT_ID=${OPEN_API_PROJECT_ID}
      - OPEN_API_ORGANIZATION_ID=${OPEN_API_ORGANIZATION_ID}
      - JIRA_ACCESS_TOKEN=${JIRA_ACCESS_TOKEN}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_URL=${JIRA_URL}
      - JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

  final-project-frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    container_name: final-project-frontend-local
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://localhost:3000/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - BACKEND_GRAPHQL_ENDPOINT=${BACKEND_GRAPHQL_ENDPOINT}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - API_KEY=${API_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LAUNCHED=${LAUNCHED}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_BUCKET_URL=${S3_BUCKET_URL}
      - SES_SENDER_EMAIL=${SES_SENDER_EMAIL}
      - SES_RECIPIENT_EMAIL=${SES_RECIPIENT_EMAIL}
      - SES_PRODUCTION=${SES_PRODUCTION}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}

  postgres:
    container_name: final-project-database-local
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase
    container_name: final-project-liquibase-local
    command: --url=${DATABASE_URL} --username=${POSTGRES_USER} --password=${POSTGRES_PASSWORD} --changelog-file=/changelogs/changelog-master.xml update
    volumes:
      - ../backend/database/src:/liquibase/src
      - ../backend/database/changelogs:/liquibase/changelogs
    depends_on:
      - "postgres"

  dynamodb:
    container_name: final-project-dynamodb-local
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  redis:
    container_name: final-project-redis-local
    image: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: final-project-zookeeper-local
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: final-project-kafka-local
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: final-project-zookeeper-local:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
