spring:
  graphql:
    graphiql:
      enabled: true
  application:
    name: backend
  security:
     oauth2:
       resourceserver:
         jwt:
           issuer-uri:
#         This should be the cognito uri that is https://cognito-idp.<aws-region>.amazonaws.com/<cognito-pool-id>
# Actuator config
management:
  endpoints:
    web:
      base-path: "/details"
    jmx:
      exposure:
        include: "health"
