stages:
  - build
  - test

before_script:
  - echo "Setting up the environment..."
  - cd ./backend/

lint_backend:
  stage: test
  image: maven:3.9.9-amazoncorretto-21-alpine
  script:
    - echo "Running backend linting..."
    - cd ./application/
    - mvn clean checkstyle:check
    - echo "Backend linting passed"

unit_test_backend:
  stage: test
  image: maven:3.9.9-amazoncorretto-21-alpine
  variables:
    TEST_COGNITO_JWT_URL: $TEST_COGNITO_JWT_URL
  script:
    - echo "Copying the test-application.yml into a application.yml file..."
    - cp ./application/backendService/src/main/resources/test-application.example.yml ./application/backendService/src/main/resources/application.yml
    - cp ./application/backendService/src/test/resources/application.example.yml ./application/backendService/src/test/resources/application.yml
    - echo "Copying completed"
    - echo "Running unit tests..."
    - cd ./application/
    - mvn -f ./backendService/pom.xml clean test -DTEST_COGNITO_JWT_URL=$TEST_COGNITO_JWT_URL
    - echo "Unit tests passed"
