image: node:23-alpine

stages:
  - lint
  - test

default:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - cd ./frontend/
    - echo "Installing dependencies..."
    - npm ci --cache .npm --prefer-offline

lint_frontend:
  stage: lint
  script:
    - echo "Running frontend linting..."
    - npm run lint

knip_frontend:
  stage: lint
  script:
    - echo "Running frontend knip..."
    - export API_KEY="Test" # Added mock api key for knip
    - npm run knip

component_test_frontend:
  stage: test
  script:
    - echo "Running frontend component tests..."
    - npm run cy:run:ct