version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ${TASK_DEFINITION}
        LoadBalancerInfo:
          ContainerName: "${ENVIRONMENT}-${SERVICE_TYPE}-container"
          ContainerPort: ${CONTAINER_PORT}
        PlatformVersion: "LATEST"
Hooks:
  BeforeAllowTraffic:
    - location: scripts/before-allow-traffic.sh
      timeout: 300
      runas: root
  AfterAllowTraffic:
    - location: scripts/after-allow-traffic.sh
      timeout: 300
      runas: root
