version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ${TASK_DEFINITION}
        LoadBalancerInfo:
          ContainerName: "${ENVIRONMENT}-${SERVICE_TYPE}-container"
          ContainerPort: ${CONTAINER_PORT}
        PlatformVersion: "LATEST"
Hooks:
  BeforeAllowTraffic:
    - LifecycleEvent: BeforeAllowTraffic
      Script: scripts/before-allow-traffic.sh
      Timeout: 300
      Runas: root
  AfterAllowTraffic:
    - LifecycleEvent: AfterAllowTraffic
      Script: scripts/after-allow-traffic.sh
      Timeout: 300
      Runas: root
